version: 2.1

# Define the jobs we want to run for this project
jobs:
  build_job:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: echo "this is the first step in the build job"
      - restore_cache:
         keys:
           - my_fancy_cache-{{ checksum "yarn.lock" }}
           - my_fancy_cache_fallback
      - run:
          name: Run yarn
          command: yarn
      - run:
          name: Run lint
          command: yarn lint
      - run:
          name: Run tsc
          command: yarn tsc
      - run: 
          name: Run jest
          command: yarn test
      - save_cache:
          key: my_fancy_cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - save_cache:
          key: my_fancy_cache
          paths:
            - ./node_modules

# Orchestrate our job run sequence
workflows:
  build_and_test_workflow:
    jobs:
      - build_job